name: Pull Request

on:
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: windows-latest
    env:
      NUGET_PACKAGES: ${{ github.workspace }}/.nuget/packages
    steps:
      - name: 🛎️ Checkout
        uses: actions/checkout@v6

      - name: ⚙️ Setup .NET
        uses: actions/setup-dotnet@v5
        with:
          dotnet-version: latest
          dotnet-channel: LTS
          cache: true

      - name: 📦 Restore
        run: dotnet restore --locked-mode

      - name: 🔨 Build
        run: dotnet build --no-restore -c Release
